// <auto-generated />
using System;
using Logistics.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistics.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704145315_AddPaymentFeesBreakdown")]
    partial class AddPaymentFeesBreakdown
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logistics.Api.Models.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ComplaintText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complaint_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LlmSuggestedResolution")
                        .HasColumnType("text")
                        .HasColumnName("llm_suggested_resolution");

                    b.Property<string>("LlmSummary")
                        .HasColumnType("text")
                        .HasColumnName("llm_summary");

                    b.Property<string>("LlmType")
                        .HasColumnType("text")
                        .HasColumnName("llm_type");

                    b.Property<Guid>("RaisedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("raised_by");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_disputes");

                    b.HasIndex("RaisedBy")
                        .HasDatabaseName("ix_disputes_raised_by");

                    b.HasIndex("ResolvedBy")
                        .HasDatabaseName("ix_disputes_resolved_by");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("ix_disputes_shipment_id");

                    b.ToTable("disputes", (string)null);
                });

            modelBuilder.Entity("Logistics.Api.Models.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveVehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_vehicle_id");

                    b.Property<string>("ApprovalReason")
                        .HasColumnType("text")
                        .HasColumnName("approval_reason");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("approval_status");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int>("CancelCount")
                        .HasColumnType("integer")
                        .HasColumnName("cancel_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CurrentLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("current_lat");

                    b.Property<decimal?>("CurrentLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("current_lng");

                    b.Property<DateTime?>("LastPingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ping_at");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_number");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operational_status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_drivers");

                    b.HasIndex("ActiveVehicleId")
                        .HasDatabaseName("ix_drivers_active_vehicle_id");

                    b.HasIndex("OperationalStatus")
                        .HasDatabaseName("ix_drivers_operational_status");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_drivers_user_id");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("Logistics.Api.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid?>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("ix_notifications_shipment_id");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_id_is_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Logistics.Api.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("Cgst")
                        .HasColumnType("numeric")
                        .HasColumnName("cgst");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DeliveryCharge")
                        .HasColumnType("numeric")
                        .HasColumnName("delivery_charge");

                    b.Property<decimal>("DriverCommission")
                        .HasColumnType("numeric")
                        .HasColumnName("driver_commission");

                    b.Property<decimal>("DriverEarnings")
                        .HasColumnType("numeric")
                        .HasColumnName("driver_earnings");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("numeric")
                        .HasColumnName("platform_fee");

                    b.Property<decimal>("Sgst")
                        .HasColumnType("numeric")
                        .HasColumnName("sgst");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_idempotency_key");

                    b.HasIndex("ShipmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_shipment_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Logistics.Api.Models.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CashCollected")
                        .HasColumnType("boolean")
                        .HasColumnName("cash_collected");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("DriverInstruction")
                        .HasColumnType("text")
                        .HasColumnName("driver_instruction");

                    b.Property<string>("DropAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("drop_address");

                    b.Property<decimal>("DropLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("drop_lat");

                    b.Property<decimal>("DropLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("drop_lng");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_id");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_type");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pickup_address");

                    b.Property<decimal>("PickupLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("pickup_lat");

                    b.Property<decimal>("PickupLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("pickup_lng");

                    b.Property<TimeOnly?>("PreferredDeliveryAfter")
                        .HasColumnType("time without time zone")
                        .HasColumnName("preferred_delivery_after");

                    b.Property<string>("PreferredWindow")
                        .HasColumnType("text")
                        .HasColumnName("preferred_window");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receiver_name");

                    b.Property<int>("ReceiverOtpAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_otp_attempts");

                    b.Property<DateTime?>("ReceiverOtpExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receiver_otp_expires_at");

                    b.Property<string>("ReceiverOtpHash")
                        .HasColumnType("text")
                        .HasColumnName("receiver_otp_hash");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receiver_phone");

                    b.Property<bool>("RiskFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("risk_flag");

                    b.Property<string>("RiskReason")
                        .HasColumnType("text")
                        .HasColumnName("risk_reason");

                    b.Property<string>("RiskSeverity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk_severity");

                    b.Property<int>("SenderOtpAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("sender_otp_attempts");

                    b.Property<DateTime?>("SenderOtpExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sender_otp_expires_at");

                    b.Property<string>("SenderOtpHash")
                        .HasColumnType("text")
                        .HasColumnName("sender_otp_hash");

                    b.Property<string>("SpecialNotes")
                        .HasColumnType("text")
                        .HasColumnName("special_notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("StatusChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("status_changed_by");

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_updated_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_shipments");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_shipments_customer_id");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_shipments_driver_id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_shipments_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_shipments_status");

                    b.HasIndex("StatusChangedBy")
                        .HasDatabaseName("ix_shipments_status_changed_by");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_shipments_vehicle_id");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("Logistics.Api.Models.Tracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.HasKey("Id")
                        .HasName("pk_tracking");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_tracking_driver_id");

                    b.HasIndex("ShipmentId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_tracking_shipment_id_recorded_at");

                    b.ToTable("tracking", (string)null);
                });

            modelBuilder.Entity("Logistics.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth0id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Auth0Id")
                        .IsUnique()
                        .HasDatabaseName("ix_users_auth0id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Logistics.Api.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_number");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_vehicles_driver_id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Logistics.Api.Models.Dispute", b =>
                {
                    b.HasOne("Logistics.Api.Models.User", "RaisedByUser")
                        .WithMany("RaisedDisputes")
                        .HasForeignKey("RaisedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_disputes_users_raised_by");

                    b.HasOne("Logistics.Api.Models.User", "ResolvedByUser")
                        .WithMany("ResolvedDisputes")
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_disputes_users_resolved_by");

                    b.HasOne("Logistics.Api.Models.Shipment", "Shipment")
                        .WithMany("Disputes")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_disputes_shipments_shipment_id");

                    b.Navigation("RaisedByUser");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Logistics.Api.Models.Driver", b =>
                {
                    b.HasOne("Logistics.Api.Models.Vehicle", "ActiveVehicle")
                        .WithMany()
                        .HasForeignKey("ActiveVehicleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_drivers_vehicles_active_vehicle_id");

                    b.HasOne("Logistics.Api.Models.User", "User")
                        .WithOne("Driver")
                        .HasForeignKey("Logistics.Api.Models.Driver", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drivers_users_user_id");

                    b.Navigation("ActiveVehicle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Logistics.Api.Models.Notification", b =>
                {
                    b.HasOne("Logistics.Api.Models.Shipment", "Shipment")
                        .WithMany("Notifications")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_shipments_shipment_id");

                    b.HasOne("Logistics.Api.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("Shipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Logistics.Api.Models.Payment", b =>
                {
                    b.HasOne("Logistics.Api.Models.Shipment", "Shipment")
                        .WithOne("Payment")
                        .HasForeignKey("Logistics.Api.Models.Payment", "ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_shipments_shipment_id");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Logistics.Api.Models.Shipment", b =>
                {
                    b.HasOne("Logistics.Api.Models.User", "Customer")
                        .WithMany("Shipments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipments_users_customer_id");

                    b.HasOne("Logistics.Api.Models.Driver", "Driver")
                        .WithMany("Shipments")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_shipments_drivers_driver_id");

                    b.HasOne("Logistics.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("StatusChangedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_shipments_users_status_changed_by");

                    b.HasOne("Logistics.Api.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_shipments_vehicles_vehicle_id");

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Logistics.Api.Models.Tracking", b =>
                {
                    b.HasOne("Logistics.Api.Models.Driver", "Driver")
                        .WithMany("TrackingPings")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tracking_drivers_driver_id");

                    b.HasOne("Logistics.Api.Models.Shipment", "Shipment")
                        .WithMany("TrackingPings")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracking_shipments_shipment_id");

                    b.Navigation("Driver");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Logistics.Api.Models.Vehicle", b =>
                {
                    b.HasOne("Logistics.Api.Models.Driver", "Driver")
                        .WithMany("Vehicles")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_drivers_driver_id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Logistics.Api.Models.Driver", b =>
                {
                    b.Navigation("Shipments");

                    b.Navigation("TrackingPings");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Logistics.Api.Models.Shipment", b =>
                {
                    b.Navigation("Disputes");

                    b.Navigation("Notifications");

                    b.Navigation("Payment");

                    b.Navigation("TrackingPings");
                });

            modelBuilder.Entity("Logistics.Api.Models.User", b =>
                {
                    b.Navigation("Driver");

                    b.Navigation("Notifications");

                    b.Navigation("RaisedDisputes");

                    b.Navigation("ResolvedDisputes");

                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
